language: node_js
node_js:
    - 8.9.1
cache:
  directories:
    - $HOME/.npm
addons:
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
    branches:
      - master
      - sonarcloud
# Send coverage data to Coveralls
after_script: "npm run coveralls"
