language: node_js
node_js:
    - 8.9.1
cache:
  directories:
    - $HOME/.npm
# Send coverage data to Coveralls
after_script: "npm run coveralls"
# Send analysis to SonarCloud
after_script: "npm run sonarqube"
