language: node_js
node_js:
    - 8.9.1
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
    - node_modules
after_script:
  # Send coverage data to Coveralls
  - "npm run coveralls"
  # Send analysis to SonarCloud
  - "npm run sonarqube"
