# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = 'docker-drone-demo'
  # login with docker/tcuser
  config.vm.box = "AlbanMontaigu/boot2docker"
#  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder "../", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    source /vagrant/vagrant/install.sh; provision
  SHELL
end
